### PR TITLE
chore: update the algorithm to verify card number

### PR DESCRIPTION
**Pull request by seyedmostafahasani**

### CODE REVIEW

**Comment by seyedmostafahasani** [comment]
@ali-master Would you please review my PR?

**Comment by ali-master** [comment]
> @ali-master Would you please review my PR?

I'll review it next week, I'm very busy these days. Thanks

**Comment by seyedmostafahasani** [comment]
> > @ali-master Would you please review my PR?
> 
> I'll review it next week, I'm very busy these days. Thanks 

No problem. Thanks!

**Comment by seyedmostafahasani** [comment]
@ali-master Hey man,
Do you have enough time to review my PR?

**Comment by mediv0** [comment]
> @ali-master Hey man, Do you have enough time to review my PR?

Could you please elaborate on what kind of improvement you've done in your RP?

did you improve time complexity ? space, cleaning the codes etc ...

**Comment by seyedmostafahasani** [comment]
> > @ali-master Hey man, Do you have enough time to review my PR?
> 
> Could you please elaborate on what kind of improvement you've done in your RP?
> 
> did you improve time complexity ? space, cleaning the codes etc ...

@ali-master I just have refactored and cleaned the code.

**Pull request closed without merging**
