### PR TITLE
persianSwear words

### PR DESCRIPTION
**Pull request by Amir-Alipour**
Hi, 
I add a feature for detect Persian swear words

* Check single word:
`persianSwear.isBad("word")`

* Check a text contain swear word:
`persianSwear.isContain("word word word")`

* Filter the swear words from text:
`persianSwear.filterSwear("word word word")` or `persianSwear.filterSwear("word word word", "++")`

* Add and remove custom word:
`persianSwear.addWord("word") |  persianSwear.removeWord("word")`

### CODE REVIEW

**Comment by moh3n9595** [comment]
Hey @Amir-Alipour, it seems your commits don't consider lint rules; please recheck them.

**Comment by Amir-Alipour** [comment]
> Hey @Amir-Alipour, it seems your commits don't consider lint rules; please recheck them.

@moh3n9595 @ali-master , Hi. i changed my code but
what's problem with prettier ?!

**Comment by ali-master** [comment]
First of all, you should care about the conventional commit messaging rules which is important to us.

**Comment by Amir-Alipour** [comment]
> First of all, you should care about the conventional commit messaging rules which is important to us.

you can explain me why the prettier refused the commit, check the code

**Comment by Amir-Alipour** [comment]
> First of all, you should care about the conventional commit messaging rules which is important to us.

can you explain me why the prettier refused the commit?, check the code pls

**Comment by ali-master** [comment]
> > Hey @Amir-Alipour, it seems your commits don't consider lint rules; please recheck them.
> 
> @moh3n9595 @ali-master , Hi. i changed my code but what's problem with prettier ?!

Run the prettier and you will see what's wrong with codes.

**Comment by Amir-Alipour** [comment]
> > > Hey @Amir-Alipour, it seems your commits don't consider lint rules; please recheck them.
> > 
> > 
> > @moh3n9595 @ali-master , Hi. i changed my code but what's problem with prettier ?!
> 
> Run the prettier and you will see what's wrong with codes.

its my error:
```
[error] No files matching the pattern were found: "'src/**/*.{ts,json}'".
```
=================
maybe for it:
```
"prettier --list-different 'src/**/*.{ts,json}' --config .prettierrc.js",
```
to
```
"prettier --list-different src/**/*.{ts,json} --config .prettierrc.js",
```

**Comment by Amir-Alipour** [comment]
> > > Hey @Amir-Alipour, it seems your commits don't consider lint rules; please recheck them.
> > 
> > 
> > @moh3n9595 @ali-master , Hi. i changed my code but what's problem with prettier ?!
> 
> Run the prettier and you will see what's wrong with codes.

hi ali, check this:
package.json :
```
"prettier:ci": "prettier --list-different 'src/**/*.{ts,json}' --config .prettierrc.js"
```
to
```
"prettier:ci": "prettier --list-different src/**/*.{ts,json} --config .prettierrc.js"
```

**Comment by Amir-Alipour** [comment]
> > > Hey @Amir-Alipour, it seems your commits don't consider lint rules; please recheck them.
> > 
> > 
> > @moh3n9595 @ali-master , Hi. i changed my code but what's problem with prettier ?!
> 
> Run the prettier and you will see what's wrong with codes.

hi @ali-master 
Screenshot (69)

**Pull request closed without merging**
